import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const matterSQ = localFont({
  src: [
    {
      path: "../assets/fonts/matterSQ-300.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/fonts/matterSQ-400.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/matterSQ-500.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/matterSQ-600.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/matterSQ-700.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/matterSQ-900.woff2",
      weight: "900",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={matterSQ.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
